apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers: 
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80