apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: myapp
        image: andrescolodrero/pythonapp:1.0.0
        volumeMounts:
        - name: config-vol
          mountPath: /config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
      volumes:
      - name: config-vol
        configMap:
          name: config-app
