apiVersion: v1
data:
  apellido: colodrero
  nombre: andres
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"apellido":"colodrero","nombre":"andres"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"dbconfig","namespace":"andres"}}
  creationTimestamp: "2023-10-11T07:36:48Z"
  name: dbconfig
  namespace: andres
  resourceVersion: "53240"
  uid: 79e142db-0958-447b-9a7b-7e3f245d56f7