# YAML example
# liveness-pod-example.yaml
#
apiVersion: v1 
kind: Pod 
metadata: 
  name: liveness-request 
spec: 
  containers: 
  - name: liveness 
    image: nginx 
    ports: 
        - containerPort: 80 
    readinessProbe: 
      httpGet: 
        path: /
        port: 80 
      initialDelaySeconds: 30 #Default 0 
      periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-liveness-with-startup-probe
  labels:
    app: readiness-liveness-with-startup-probe
spec:
  ports:
    - port: 80
  selector:
    app: readiness-liveness-with-startup-probe
  type: ClusterIP 