apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness
  labels:
    app: readiness
    
spec:
  selector:
    matchLabels:
      app: readiness
  template:
    metadata:
      labels:
        app: readiness
    spec:
      containers:
      - name: nginx
        image: nginx
        # imagePullPolicy: IfNotPresent
        ports:
        - name: http 
          containerPort: 80
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 5m
            memory: 20Mi
        readinessProbe:
          httpGet:
            path: /startupcheck.txt
            port: 80
          initialDelaySeconds: 30 #Default 0 
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: readiness
  labels:
    app: readiness
spec:
  ports:
    - port: 80
  selector:
    app: readiness
  type: ClusterIP 