apiVersion: v1 
kind: Pod 
metadata: 
  name: liveness-tcpsocket
spec: 
  containers: 
  - name: liveness 
    image: nginx 
    ports: 
        - containerPort: 80 
    livenessProbe: 
      tcpSocket:
        port: 80
      initialDelaySeconds: 20  #Default 0 
      periodSeconds: 2 #Default 10 
      timeoutSeconds: 1 #Default 1 
      successThreshold: 1 #Default 1 
      failureThreshold: 3 #Default 3