apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
spec:
  volumeMode: Filesystem
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    #path: "/mnt/wsl/data"
    #path: "/run/desktop/mnt/host/wsl/data/" -> funciona pero no veo el host
    path: "/var/lib/docker/volumes/test/_data"