apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud
            operator: NotIn
            values:
            - Azure            
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
