apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        env: 
          - name: CONTAINER_NAME
            value: "hello"
        image: andrescolodrero/rio
        ports:
        - containerPort: 80
