apiVersion: v1
kind: Pod
metadata:
  name: nginx-taint
  labels:
    env: test
spec:
  containers:
  - name: nginx-taint
    image: nginx
  tolerations:
  - key: "key1"
    operator: "Exists"
    effect: "NoSchedule"

