apiVersion: v1
kind: Pod
metadata:
  name: mipod
  labels:
    name: mmi-label
spec:
  containers:
  - name: micontendor
    image: quay.io/redhattraining/php-webapp
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
