apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1.10
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        name: "nginx"
        version: "1-10"
    spec:
      containers:
      - name: myapp
        image: nginx:1.10
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
