# node-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: nodejs-app
        image: mercybassey/memory-leak  
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health-check  
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          limits:
            memory: "400Mi"
            cpu: "400m"    
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: node-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000