apiVersion: v1
kind: Pod
metadata:
  namespace: andres
  name: two-containers
spec:
  restartPolicy: Never
  containers:
  - name: nginx-container
    image: nginx
    ports:
     - containerPort: 8081

  - name: debian-container
    image: andrescolodrero/pythonapp:1.0.0
    ports:
     - containerPort: 8080
